var car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == "subaru");
console.log("Is car === 'subaru'? I predict True.");
console.log(car === "subaru");
console.log("Is car == 'Corolla'? I predict False.");
console.log(car == "Corolla");
console.log("Is car === 'Corolla'? I predict False.");
console.log(car === "Corolla");
console.log("Is car != 'Corolla'? I predict True.");
console.log(car != "Corolla");
console.log("Is car != 'Subaru'? I predict False.");
console.log(car != "subaru");
console.log("Is car == 'SUBARU'? I predict False.");
console.log(car == "SUBARU");
console.log("Is car != 'SUBARU'? I predict True.");
console.log(car != "SUBARU");
console.log("Is car === 'SUBARU'? I predict False.");
console.log(car == "SUBARU");
console.log("Is car !== 'SUBARU'? I predict True.");
console.log(car != "SUBARU");
